-   id: beancount-check
    name: beancount-check
    entry: bean-check
    language: python
    files: .*(\.bean|\.beancount|\.ledger)$
    require_serial: true
    additional_dependencies: [beancount]
